# -*- coding: utf-8 -*-
"""Copy of July_16_KNN_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fP_j8MUurcne9_fRiq2ZrwB5KGXvOLxi

# K-Nearest Neighbors Classification: Predicting College Admission

## Goal
In this activity, you will use **K-nearest neighbors (KNN)** to predict whether a student is admitted to a college based on two exam scores.

You will build the model yourself, then use scikit-learn to check whether your implementation reaches the same results.

By the end, you should be able to:

1. Explain how KNN makes a classification.
2. Calculate Euclidean distance.
3. Find the nearest training examples.
4. Use majority voting to predict a class.
5. Explain what the value of `k` controls.
6. Measure the model's accuracy.
7. Describe a KNN decision boundary.
8. Compare a hand-built model with a reference implementation.

## What you need to know
You only need basic Python skills:

- running notebook cells
- reading variables
- changing a small amount of code
- interpreting graphs and numbers

All required data are created inside this notebook. No files need to be downloaded.

## 1. Setup

Run the cell below. It imports the tools used in this notebook.

- **NumPy** creates and stores numerical data.
- **Matplotlib** makes graphs.
- **scikit-learn** is used only at the end to check our work.

The main KNN model will be built using NumPy.
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Make random results repeatable.
np.random.seed(7)

print("Setup complete!")

"""## 2. Create the data

Each student has:

- an Exam 1 score
- an Exam 2 score
- an admission result: `0` means not admitted and `1` means admitted

The code below creates a small, realistic-looking dataset. The admission results are not perfectly predictable, just like real data.

"""

number_of_students = 120

exam_1 = np.random.randint(45, 101, number_of_students)
exam_2 = np.random.randint(45, 101, number_of_students)

# Higher combined scores usually mean a better chance of admission.
combined_score = exam_1 + exam_2
random_noise = np.random.normal(0, 10, number_of_students)
admitted = (combined_score + random_noise >= 145).astype(int)

# X contains the two input features. y contains the yes/no result.
X = np.column_stack((exam_1, exam_2))
y = admitted

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)
print("First five students:")
print(X[:5])
print("First five results:", y[:5])

"""### Question 1

What does one row of `X` represent? What does one value of `y` represent?

**Your answer:**

One row of X represents the two exam scores. One value of y represents whether the student got into college.

## 3. Visualize the data

A scatter plot helps us see whether admitted and non-admitted students tend to have different exam scores.
"""

not_admitted = y == 0
is_admitted = y == 1

plt.figure(figsize=(8, 6))
plt.scatter(X[not_admitted, 0], X[not_admitted, 1],
            label="Not admitted", marker="o")
plt.scatter(X[is_admitted, 0], X[is_admitted, 1],
            label="Admitted", marker="+")

plt.xlabel("Exam 1 score")
plt.ylabel("Exam 2 score")
plt.title("College Admission Data")
plt.legend()
plt.grid(True)
plt.show()

"""### Question 2

Describe the pattern in the graph. Do students with higher scores appear more likely to be admitted?

**Your answer:**

Students with higher scores appear more likely to be admitted.

## 4. Why K-nearest neighbors?

KNN predicts a new student's class by comparing that student with the training students.

For one new student, the algorithm:

1. Calculates the distance to every training student.
2. Selects the `k` closest students.
3. Looks at their admission results.
4. Predicts the class that appears most often.

We will use **Euclidean distance**:

$$
d = \sqrt{(x_1-a_1)^2 + (x_2-a_2)^2}
$$

Here, the two coordinates are the two exam scores.
"""

def euclidean_distance(point_1, point_2):
    squared_difference = (point_1 - point_2) ** 2
    return np.sqrt(np.sum(squared_difference))

student_a = np.array([70, 80])
student_b = np.array([74, 83])

distance = euclidean_distance(student_a, student_b)

print("Student A:", student_a)
print("Student B:", student_b)
print("Euclidean distance:", round(distance, 3))

"""### Question 3

If the five nearest neighbors contain three admitted students and two non-admitted students, what class will KNN predict?

**Your answer:**

The KNN will predict admitted.

## 5. Split the data

We will use:

- **training data** as the examples KNN searches through
- **test data** to check the model on students it has not seen before

Here, 75% of the students are used for training and 25% are used for testing.
"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=7,
    stratify=y
)

print("Training students:", len(X_train))
print("Testing students:", len(X_test))

"""### Question 4

Why should we test the model on students that were not included in its training examples?

**Your answer:**

The model should be tested on the student that were not included in the training to see if it actually predicts the sample right from an unused population.

## 6. Build KNN ourselves

KNN does not learn weights. Its `fit()` method stores the training data.

When predicting one new student, it:

1. Calculates the distance from the new student to every training student.
2. Sorts the distances from smallest to largest.
3. Keeps the first `k` students.
4. Uses majority voting to predict the class.

### Scale the exam scores

KNN is based entirely on distance. A feature with a larger numerical scale can dominate the distance calculation.

We calculate the mean and standard deviation from the **training data only**, then use those same values for both the training and test data.
"""

feature_mean = X_train.mean(axis=0)
feature_std = X_train.std(axis=0)

X_train_scaled = (X_train - feature_mean) / feature_std
X_test_scaled = (X_test - feature_mean) / feature_std

print("Mean of scaled training data:",
      np.round(X_train_scaled.mean(axis=0), 3))
print("Standard deviation of scaled training data:",
      np.round(X_train_scaled.std(axis=0), 3))

"""### How prediction works

For one new point $x$, calculate its distance to every training point $x_i$:

$$
d_i = \sqrt{\sum_j (x_j-x_{ij})^2}
$$

Sort the distances and keep the indices of the `k` smallest values.

For binary classification, the predicted probability of admission is the fraction of those neighbors whose label is `1`:

$$
P(y=1) = \frac{\text{number of admitted neighbors}}{k}
$$

The final prediction is `1` when at least half of the neighbors are admitted.

"""

class MyKNN:
    def __init__(self, k=5):
        self.k = k

    def fit(self, X, y):
        # KNN training only stores the examples.
        self.X_train = X
        self.y_train = y
        return self

    def _neighbor_labels(self, new_student):
        # Step 1: calculate the distance to every training student.
        differences = self.X_train - new_student
        distances = np.sqrt(np.sum(differences ** 2, axis=1))

        # Step 2: sort the distances from smallest to largest.
        sorted_indices = np.argsort(distances)

        # Step 3: keep the k nearest training students.
        nearest_indices = sorted_indices[:self.k]
        neighbor_labels = self.y_train[nearest_indices]

        return neighbor_labels

    def predict_proba(self, X):
        probabilities = []

        for new_student in X:
            neighbor_labels = self._neighbor_labels(new_student)

            # Step 4: the fraction of neighbors in class 1.
            admission_probability = np.mean(neighbor_labels == 1)
            probabilities.append(
                [1 - admission_probability, admission_probability]
            )

        return np.array(probabilities)

    def predict(self, X):
        admission_probability = self.predict_proba(X)[:, 1]
        return (admission_probability >= 0.5).astype(int)

"""class MyKNN:
    def __init__(self, k=5):
        self.k = k

    def fit(self, X, y):
        # TODO 1: Store the training features and labels.
        self.X_train = ...
        self.y_train = ...
        return self

    def _neighbor_labels(self, new_student):
        # TODO 2: Subtract the new student from every training student.
        differences = ...

        # TODO 3: Calculate one Euclidean distance per training student.
        distances = ...

        # TODO 4: Sort the distances from smallest to largest.
        sorted_indices = ...

        # TODO 5: Keep only the first k indices.
        nearest_indices = ...

        # TODO 6: Use those indices to retrieve the neighbor labels.
        neighbor_labels = ...

        return neighbor_labels

    def predict_proba(self, X):
        probabilities = []

        for new_student in X:
            neighbor_labels = self._neighbor_labels(new_student)

            # TODO 7: Find the fraction of neighbor labels equal to 1.
            admission_probability = ...

            probabilities.append(
                [1 - admission_probability, admission_probability]
            )

        return np.array(probabilities)

    def predict(self, X):
        admission_probability = self.predict_proba(X)[:, 1]

        # TODO 8: Predict class 1 when the probability is at least 0.5.
        return ...

### Fill-in hints

You may use:

```python
self.X_train - new_student
np.sqrt(np.sum(... ** 2, axis=1))
np.argsort(...)
sorted_indices[:self.k]
self.y_train[nearest_indices]
np.mean(neighbor_labels == 1)
(admission_probability >= 0.5).astype(int)
```

Each expression is used once.

## 7. Fit the model

The value of `k` controls how many neighbors vote.

- A very small `k` can make the model sensitive to individual training points.
- A larger `k` produces a smoother, more stable decision.
"""

model = MyKNN(k=3)
model.fit(X_train_scaled, y_train)

print("The model has stored the training data.")
print("Number of stored students:", len(model.X_train))
print("k:", model.k)

"""### Inspect one set of neighbors

The cell below finds the five nearest training students for the first test student.

"""

first_test_student = X_test_scaled[0]

differences = model.X_train - first_test_student
distances = np.sqrt(np.sum(differences ** 2, axis=1))
nearest_indices = np.argsort(distances)[:model.k]

print("First test student:", X_test[0])
print("Nearest training students:")
print(X_train[nearest_indices])
print("Neighbor labels:", y_train[nearest_indices])

"""### Question 6

How many of the nearest neighbors were admitted? Based on majority voting, what class should the model predict?

**Your answer:**

4 of the nearest neighbors were admitted. The model should predict admitted.

## 8. Make predictions

`predict()` gives a final class, either `0` or `1`.

`predict_proba()` gives the fraction of nearest neighbors in each class.
"""

predicted_classes = model.predict(X_test_scaled)
predicted_probabilities = model.predict_proba(X_test_scaled)

print("First five test students:")
print(X_test[:5])
print()
print("Predicted classes:", predicted_classes[:5])
print("Fraction of neighbors admitted:",
      np.round(predicted_probabilities[:5, 1], 3))
print("Actual results:", y_test[:5])

"""### Question 7

For the first test student, compare the neighbor fraction, predicted class, and actual result. Was the model correct?

**Your answer:**

The neighbor fraction was 0.8, the predicted class is admitted, and the actual result was not admitted. The model was incorrect.

## 9. Evaluate the model

Accuracy is the fraction of predictions that are correct.

A confusion matrix counts four types of results:

- true negatives: correctly predicted not admitted
- false positives: predicted admitted, but actually not admitted
- false negatives: predicted not admitted, but actually admitted
- true positives: correctly predicted admitted
"""

accuracy = accuracy_score(y_test, predicted_classes)
matrix = confusion_matrix(y_test, predicted_classes)

print("Accuracy:", round(accuracy, 3))
print("Accuracy as a percent:", round(accuracy * 100, 1), "%")
print()
print("Confusion matrix:")
print(matrix)

"""### Question 8

1. What percent of the test predictions were correct?
2. How many test students were classified incorrectly?

Hint: the incorrect predictions are the two off-diagonal values in the confusion matrix.

**Your answer:**

76 percent of the test predicitons were correct. 7 Students were classified incorrectly.

## 10. Check our work with scikit-learn

Now we will train scikit-learn's KNN classifier using the exact same training data, test data, scaling, and value of `k`.

Because both implementations use the same algorithm, their predictions should match.
"""

reference_model = KNeighborsClassifier(n_neighbors=5)
reference_model.fit(X_train_scaled, y_train)

reference_classes = reference_model.predict(X_test_scaled)
reference_probabilities = reference_model.predict_proba(X_test_scaled)

reference_accuracy = accuracy_score(y_test, reference_classes)
prediction_agreement = np.mean(
    predicted_classes == reference_classes
)
average_probability_difference = np.mean(
    np.abs(
        predicted_probabilities[:, 1]
        - reference_probabilities[:, 1]
    )
)

print("Our model accuracy:",
      round(accuracy, 3))
print("scikit-learn accuracy:",
      round(reference_accuracy, 3))
print("Prediction agreement:",
      round(prediction_agreement * 100, 1), "%")
print("Average probability difference:",
      round(average_probability_difference, 4))

"""### Question 9

Do the two implementations produce the same accuracy and predictions?

Would you consider the hand-built implementation successful? Explain.

**Your answer:**

The two implementations have the same accuracy and predictions. The hand-built implementation is successful because it has the same prediction, or a prediction agreement of 100%.

## 11. Try your own student

Change the two exam scores below, then run the cell.

New students must be scaled using the same mean and standard deviation that were calculated from the training data.
"""

student_exam_1 = 22
student_exam_2 =82

new_student = np.array([[student_exam_1, student_exam_2]])
new_student_scaled = (
    new_student - feature_mean
) / feature_std

admission_probability = model.predict_proba(
    new_student_scaled
)[0, 1]
predicted_result = model.predict(
    new_student_scaled
)[0]

print("Fraction of nearest neighbors admitted:",
      round(admission_probability * 100, 1), "%")
print("Predicted class:", predicted_result)

if predicted_result == 1:
    print("Prediction: admitted")
else:
    print("Prediction: not admitted")

"""### Question 10

Try at least three pairs of exam scores. Record the results below.

| Exam 1 | Exam 2 | Fraction of neighbors admitted | Predicted class |
|---:|---:|---:|---:|
| | | | |
| | | | |
| | | | |

What pattern do you notice?

**Your answer:**

1) 22,82, 0, 0
2) 44, 88, 60, 1
3) 99,99, 100, 1
I noticed that the higher the test scores are the more likely they are able to be admitted. Furthermore, the fraction of nearest neighbors increases as score increase.

## 12. Plot the decision boundaries

A **decision boundary** is where a model changes from predicting class `0` to predicting class `1`.

KNN boundaries can bend around groups of training points because the prediction depends on nearby examples rather than one straight equation.

The solid line is the boundary from our model. The dashed line is the boundary from scikit-learn.
"""

from matplotlib.lines import Line2D

# Create a grid of possible exam-score pairs.
exam_1_grid = np.linspace(45, 100, 150)
exam_2_grid = np.linspace(45, 100, 150)
grid_x, grid_y = np.meshgrid(
    exam_1_grid,
    exam_2_grid
)

grid_points = np.column_stack(
    (grid_x.ravel(), grid_y.ravel())
)
grid_points_scaled = (
    grid_points - feature_mean
) / feature_std

our_grid_class = model.predict(
    grid_points_scaled
).reshape(grid_x.shape)

reference_grid_class = reference_model.predict(
    grid_points_scaled
).reshape(grid_x.shape)

plt.figure(figsize=(8, 6))
plt.scatter(
    X[not_admitted, 0],
    X[not_admitted, 1],
    label="Not admitted",
    marker="o"
)
plt.scatter(
    X[is_admitted, 0],
    X[is_admitted, 1],
    label="Admitted",
    marker="+"
)

plt.contour(
    grid_x,
    grid_y,
    our_grid_class,
    levels=[0.5],
    linestyles="-"
)
plt.contour(
    grid_x,
    grid_y,
    reference_grid_class,
    levels=[0.5],
    linestyles="--"
)

handles, labels = plt.gca().get_legend_handles_labels()
boundary_handles = [
    Line2D([0], [0], linestyle="-",
           label="Our model"),
    Line2D([0], [0], linestyle="--",
           label="scikit-learn")
]
plt.legend(handles=handles + boundary_handles)

plt.xlabel("Exam 1 score")
plt.ylabel("Exam 2 score")
plt.title("KNN Decision Boundary Comparison")
plt.grid(True)
plt.show()

"""### Question 11

1. What does each decision boundary separate?
2. Do the two boundary lines overlap?
3. Why is the KNN boundary less straight than a logistic regression boundary?
4. Why might some data points appear on the "wrong" side of the boundary?

**Your answer:**

Each boundary seperates admitted students and not admitted students. The lines overlap because they have 100% agreement. The KNN boundary is less straight than a logisistic regression because it clusters items by where they are in space rather than using a sigmoid function. Some data points appear on the wrong side of the boundary because their nearest neighbors that are around it are the opposite of what it is.

## 13. Final reflection

Answer each question in one or two sentences.

1. How does KNN classify a new student?
2. What does `k` control?
3. Why is scaling important for KNN?
4. What is the difference between the neighbor fraction and the predicted class?
5. Why did we compare our model with scikit-learn?
6. Does high accuracy prove that a model will always be correct? Explain.

**Your answer:**

The KNN classifies a new student by looking at the nearest students around it and taking the majority of the the participants' status. K controls the number of student it takes to determine how many neighbors. The scaling is important because it allows every value to have equal weight. The difference between the neighbor fraction and predicted class is that the neighbor fraction is from 0 to 1 and the predicted class must be either 0 or 1. The model is compared to show that doing the writing manually is the same as the function. High accuracy does not prove that am model will always be correct because overfitting can occur and extremeities and outliers can occur as well.

## Optional challenge: compare different values of k

Run the cell below and compare several values of `k`.

Look at:

- test accuracy
- how smooth or irregular the decision boundary becomes
- whether a very small or very large `k` performs best

What happens when `k = 1`? What happens when `k` becomes much larger?
"""

k_values = [1, 3, 5, 9, 15, 25,29,37,50]

for k in k_values:
    test_model = MyKNN(k=k)
    test_model.fit(X_train_scaled, y_train)
    test_predictions = test_model.predict(X_test_scaled)
    test_accuracy = accuracy_score(y_test, test_predictions)

    print("k =", str(k).rjust(2),
          "| accuracy =", round(test_accuracy, 3))